name: Code Analysis

on:
    pull_request: null
    push: null

jobs:
    tests:
        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            -   uses: actions/checkout@v3

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: php Example.php